

service: acution-service

frameworkVersion: '2'

# plugins:
#   - serverless-bundle

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  lambdaHashingVersion: 20201221
  stage: ${opt:stage,'dev'}
  region: ap-southeast-1
  iamRoleStatements:
    - ${file(iam/ActionsTableIAM.yml):ActionsTableIAM}
      
functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction

custom:
  bundle:
    linting: false

resources:
  Resources:
    AuctionTable: ${file(resources/AuctionTable.yml):AuctionTable}