

service: acution-service

frameworkVersion: '2'

# plugins:
#   - serverless-bundle

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  lambdaHashingVersion: 20201221
  stage: ${opt:stage,'dev'}
  region: ap-southeast-1
  iamRoleStatements:
    - ${file(iam/ActionsTableIAM.yml):ActionsTableIAM}
  environment:
    AUCTION_TABLE_NAME: ${self:custom.AuctionTable.name}
      
functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction
  getAuction:
    handler: src/handlers/getAuction.handler
    events:
      - http:
          method: GET
          path: /auction
  getAuctionById:
    handler: src/handlers/getAuctionById.handler
    events:
      - http:
          method: GET
          path: /auction/{id}

custom:
  bundle:
    linting: false
  AuctionTable:
    name: !Ref AuctionTable
    arn: !GetAtt AuctionTable.Arn

resources:
  Resources:
    AuctionTable: ${file(resources/AuctionTable.yml):AuctionTable}